# Homework 9

## Oscar Galindo

## SP4
write a program that does forward elimination-use the naive method

In [4]:
import numpy as np

def forward_elim(A,B):
    n = len(B)
    for i in range(0,n):
        for j in range(i+1, n):
            factor = A[j, i]/A[i,j]
            B[j] = B[j] - factor*B[i]
            for k in range(i,n):
                if A[j,k] !=0.0:
                    A[j,k] = A[j,k] - factor*A[i,k]
    return print(f"A:\n{A}\nB:\n{B}")

A = np.array([[2,-2,1],[3,2,-5],[-1,2,3]], dtype=float)
B = np.array([10,-16,8], dtype=float)
print(f"Answer for SP1")
forward_elim(A,B)
A = np.array([[2,1,-1,2],[1,-2,1,-4],[3,-1,-2,-1],[-1,2,1,-2]])
B = np.array([0,3,-3,13], dtype=float)
print("\nAnswer for SP2")
forward_elim(A,B)


Answer for SP1
A:
[[ 2.  -2.   1. ]
 [ 6.  -1.  -3.5]
 [ 1.   0.   4. ]]
B:
[10. -1. 18.]

Answer for SP2
A:
[[ 2  1 -1  2]
 [-1 -3  2 -6]
 [ 9  5 -7 11]
 [ 0  1  0 -3]]
B:
[ 0.  3. -6. 14.]


## SP5
combine your programs that performed forward elimination and back substitution so that the solution vector for [x] is printed out.

In [10]:
import numpy as np

def Gauss(A,B):
    n = len(B)
    for i in range(0, n):
        for j in range(i+1, n):
            factor = A[j,i]/A[i,i]
            B[j] = B[j] - factor*B[i]
            for k in range(i, n):
                if A[j, k] != 0.0:
                    A[j, k] = A[j, k] - factor * A[i, k]
    for k in range(n-1, -1,-1):
        B[k] = (B[k] - np.dot(A[k,k+1:n], B[k+1:n]))/A[k,k]
    return print(B)

A = np.array([[2,-2,1],[3,2,-5],[-1,2,3]], dtype=float)
B = np.array([10,-16,8], dtype=float)
print(f"Answer for SP1")
Gauss(A,B)
A = np.array([[2,1,-1,2],[1,-2,1,-4],[3,-1,-2,-1],[-1,2,1,-2]], dtype=float)
B = np.array([0,3,-3,13], dtype=float)
print("Answer for SP2")
Gauss(A,B)


Answer for SP1
[ 2. -1.  4.]
Answer for SP2
[ 1.  4.  2. -2.]


## SP6
modify your program form SP5 to perform Gauss-Jordan elimination. 

In [3]:
import numpy as np
def GaussJordan(A,B):
    n = len(B)
    for k in range(n):
        if np.fabs(A[k,k])<1.0e-12:
            for i in range(k+1, n):
                if np.fabs(A[i,k])> np.fabs(A[k,k]):
                    for j in range(k, n):
                        A[k, j], A[i, j] = A[i, j], A[k, j]
                    B[k], B[i] = B[i], B[k]
                    break
        pivot = A[k, k]
        for j in range(k, n):
            A[k, j] /= pivot
        B[k] /= pivot
        for i in range(n):
            if i == k or A[i, k] == 0: continue
            ratio = A[i, k]
            B[i] -= ratio * B[k]
            for j in range(k, n):
                A[i, j] -= ratio * A[k, j]
    for k in range(n-1, -1, -1):
        B[k] = (B[k]- np.dot(A[k, k+1:n], B[k+1:n]))/ A[k, k]
    return print(A, B)
    
A = np.array([[4,3,2,1],[2,-1,2,-4],[1,2,-2,-1],[-2,4,5,-1]], dtype=float)
B = np.array([17,11,8,15], dtype=float)
print("Answer for SP3")
GaussJordan(A,B)

Answer for SP3
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] [ 2.  3.  1. -2.]
